### DISCUSSION TITLE
Ping feature should support pinging hosts by name

### DISCUSSION THREAD

**Discussion by jhol** [seriousm4x/UpSnap#386] [Feature requests]
The ping feature currently only supports pinging hosts by their IP addresses. On my network, my non-server machines use non-static DHCP, but with mDNS. Therefore I need to be able to ping host by host name e.g. `mypc.local`.

**Comment by seriousm4x** [comment]
This is already possible. The input fields are labeled as `IP` but you can also enter a fqdn. I just checked on my local instance.

**Comment by jhol** [comment]
Weird - I tried doing that earlier, but it gave me errors.

```
[ERROR] 2023/12/31 12:38:49 ping.go:16: lookup nethermost.local: device or resource busy
```

Anyway, if this is supposed to work, I think the label could be clearer.

**Comment by ProsperAdmin** [comment]
I'm also unable to ping by Hostname/FQDN/mDNS. Log says this every 3s for every host with an address instead of an IP:
```
[ERROR] 2024/02/17 11:42:35 ping.go:21: lookup DESKTOP.local on 127.0.0.53:53: server misbehaving
```

And if I manually try to wake up that host (which is already turned on, btw):
```
[INFO] 2024/02/17 11:42:36 wake.go:16: Wake triggered for My PC
[ERROR] 2024/02/17 11:42:36 handlers.go:31: ip not a valid ipv4 address
```

Same thing for a host that is actually turned off:
```
[ERROR] 2024/02/17 11:49:02 ping.go:21: lookup DESKTOP-JANE.local on 127.0.0.53:53: server misbehaving
[INFO] 2024/02/17 11:49:03 wake.go:16: Wake triggered for Jane PC
[ERROR] 2024/02/17 11:49:03 handlers.go:31: ip not a valid ipv4 address
[ERROR] 2024/02/17 11:49:05 ping.go:21: lookup DESKTOP-JANE.local on 127.0.0.53:53: server misbehaving
```

If I use an actual IP instead of a name, everything works fine

Using UpSnap 4.2.5 in a Docker container (via Portainer "stack"), with the following composer file:
```
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - data:/app/pb_data
    environment:
      - TZ=America/Sao_Paulo
volumes:
  data:
```

Host is an Ubuntu 22.04 server with `systemd-resolved` active at default settings, and I can ping both machines by name, i.e. `ping DESKTOP.local` works fine from host.

Any ideas?

**Comment by seriousm4x** [comment]
I did a little research what the issue here could be. I think it's an issue with docker using the host network: https://github.com/moby/moby/issues/38531

Maybe explicitly telling docker what dns to use will fix it. For  you docker-composer.yml, try:

```yml
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    dns:
      - 192.168.0.1
```

Or `docker run --dns 192.168.0.1 ....`
