### DISCUSSION TITLE
Problem with WOL and scanning in another VLAN

### DISCUSSION THREAD

**Discussion by info-path** [seriousm4x/UpSnap#406] [Help wanted]
I have UpSnap installed in Docker as a HOST, scanning and WOL works correctly if I am in the same subnet, e.g. `192.168.1.0/24`.

But WOL doesn't work if I specify a PC from a different subnet, e.g. `192.168.5.2`, and neither does scanning the `192.168.5.0/24 `subnet. The Firewal is disabled, pinging to `192.168.5.0/24` from terminal on Ubuntu with Docker and UpSnap works.

My docker-compose:
```
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:3
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=Europe/Berlin
      - UPSNAP_INTERVAL=@every 5s # Sets the interval in which the devices are pinged
      - UPSNAP_SCAN_RANGE=192.168.0.0/16 # Scan range is used for device discovery on local network
```

What am I doing wrong? Can I use WOL on another subnet?
