### DISCUSSION TITLE
All configuration as file

### DISCUSSION THREAD

**Discussion by Tchoupinax** [seriousm4x/UpSnap#469] [Feature requests]
Hello,

I was looking for this kind of project (or doing it) and `UpSnap` looks pretty well. One feature I would like is the ability to configure the service with a config file because I believe deeply in IaC.
It could start by referencing all added devices and these devices are immutable if they are managed by the configuration.

I would like your opinion before starting the implementation and if this thing has could belong to this project.

Let's see an hypothetical exemple:

```yaml
devices:
  - name: "NAS"
     IP: 192.168.1.34
     macAddress: 11:22:33:44:55
     netmask: 255.255.255.0
    [...]
  - name: "Kodi"
     IP: 192.168.1.35
     macAddress: 11:22:33:44:55
     netmask: 255.255.255.0
    [...]
```
