### ISSUE TITLE
Cron syntax validation

### ISSUE THREAD

**Issue by KeitaroDPVF** [seriousm4x/UpSnap#1043]
### The bug

A validation logic mistake, restricting the minutes to a range of 0-23 instead of 0-59.

### The OS that UpSnap is running on

Ubuntu 24.04

### Version of UpSnap

5.0.2

### Your docker-compose.yml content

```YAML
services:
  upsnap:
    container_name: upsnap
    image: seriousm4x/upsnap:5
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:80"
    healthcheck:
      test: curl -fs "http://localhost:80/api/health" || exit 1
      interval: 10s
```

### Reproduction steps

```bash
1.Enable Wake/shutdown cron
2.Input Wake/Shutdown cron:
59 23 7 * * *  --> Mar 19, 2025, 7:23:59 AM
59 24 7 * * *  --> Invalid cron syntax

Same as Ping interval.
```
