### ISSUE TITLE
[BUG] The language change cannot be saved

### ISSUE THREAD

**Issue by charley008** [seriousm4x/UpSnap#1045]
### The bug

Every time I close the browser and reopen the Upsnap, the language reverts to English, even though I have changed it to another language in the language settings.

### The OS that UpSnap is running on

synology nas 920+

### Version of UpSnap

5.0.3

### Your docker-compose.yml content

```YAML
services:
  upsnap:
    container_name: upsnap
    image: seriousm4x/upsnap:latest
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai # Adjust to your timezone
      - UPSNAP_INTERVAL=@every 10s
      - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Adjust to your network
      - UPSNAP_SCAN_TIMEOUT=500ms
      - UPSNAP_PING_PRIVILEGED=true
      - PUID=1024
      - PGID=100
    volumes:
       - /volume1/docker/upsnap:/app/pb_data
    entrypoint: /bin/sh -c "./upsnap serve --http 127.0.0.1:8091"
    healthcheck:
      test: curl -fs "http://127.0.0.1:8091/api/health" || exit 1
      interval: 1000s
```
