### ISSUE TITLE
[BUG] Linux shutdown command does not work

### ISSUE THREAD

**Issue by h4km4k** [seriousm4x/UpSnap#1082]
### The bug

Your example now is:

`sshpass -p password ssh -o "StrictHostKeyChecking=no" user@192.168.1.13 "sudo poweroff`

This will not work.

If you make a small change it will work with every user except root:

`sshpass -p password ssh -o "StrictHostKeyChecking=no" user@192.168.1.13 "echo password | sudo -S poweroff`

For the root user (without sudo installed):

`sshpass -p password ssh -o "StrictHostKeyChecking=no" root@192.168.1.13 "poweroff`

### The OS that UpSnap is running on

Ubuntu 24.04 - Docker

### Version of UpSnap

5.0

### Your docker-compose.yml content

```YAML
services:
  upsnap:
    container_name: upsnap
    #image: ghcr.io/seriousm4x/upsnap:4 # images are also available on docker hub: seriousm4x/upsnap:4
    image: seriousm4x/upsnap:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    # # To use a non-root user, create the mountpoint first (mkdir data) so that it has the right permission.
    #user: 1000:1000
    environment:
       - TZ=Europe/Berlin # Set container timezone for cron schedules
       - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
    #   - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
    #   - UPSNAP_SCAN_TIMEOUT=500ms # Scan timeout is nmap's --host-timeout value to wait for devices (https://nmap.org/book/man-performance.html)
    #   - UPSNAP_PING_PRIVILEGED=false # Set to false if you don't have root user permissions
    #   - UPSNAP_WEBSITE_TITLE=Custom name # Custom website title
    # # dns is used for name resolution during network scan
    dns:
       - 192.168.178.1
    #   - 192.18.0.2
    # # you can change the listen ip:port inside the container like this:
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    healthcheck:
       test: curl -fs "http://localhost:5000/api/health" || exit 1
       interval: 60s
    # # or install custom packages for shutdown
    # entrypoint: /bin/sh -c "apk update && apk add --no-cache <YOUR_PACKAGE> && rm -rf /var/cache/apk/* && ./upsnap serve --http 0.0.0.0:8090"
```
