### ISSUE TITLE
[BUG] Refreshing the page logout authenticated users and redirects to login

### ISSUE THREAD

**Issue by pavelpikta** [seriousm4x/UpSnap#1158]
### The bug

When a user clicks the browser's refresh button while logged in, the current authenticated session is unexpectedly terminated. The user is then redirected to the login page, and the session cannot be restored without re-authentication.

### The OS that UpSnap is running on

Ubuntu-22.04

### Version of UpSnap

5.0.7

### Your docker-compose.yml content

```YAML
---
services:
  wol:
    container_name: wol
    image: ghcr.io/seriousm4x/upsnap:5.0.7
    network_mode: host
    dns:
      - <REDACTED>
    restart: always
    volumes:
      - $APP_DIR/wol:/app/pb_data
    environment:
      - TZ=$TZ # Set container timezone for cron schedules
      - UPSNAP_INTERVAL=*/10 * * * * * # Sets the interval in which the devices are pinged
      - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
      - UPSNAP_SCAN_TIMEOUT=500ms # Scan timeout is nmap's --host-timeout value to wait for devices (https://nmap.org/book/man-performance.html)
      - UPSNAP_PING_PRIVILEGED=true # Set to false if you don't have root user permissions
      - UPSNAP_WEBSITE_TITLE=WOL # Custom website title
    # you can change the listen ip:port inside the container like this:
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:60001"
    healthcheck:
      test: curl -fs "http://localhost:60001/api/health" || exit 1
      interval: 10s
```

### Reproduction steps

```bash
1. Log in to the application.
2. Click the browser's refresh button.
3. Observe that the session ends and the user is redirected to the login screen.
```

### Additional information

This issue may be related to how session tokens or cookies are handled on page reload.
