### ISSUE TITLE
[BUG] something strange happens in the interface

### ISSUE THREAD

**Issue by domenico-dig** [seriousm4x/UpSnap#1168]
### The bug

When pc is **OFF** see power button **GREEN** and rdp **RED** and that doesn't allow me to turn it on

![Image](https://github.com/user-attachments/assets/6af672b6-a643-4c89-81d9-01dc1168a1b8)

When pc is **ON** and i see power button **RED** and rdp ** GREEN** when pc is **ON**, 

![Image](https://github.com/user-attachments/assets/889d94b9-72ff-4fb6-b496-73057985ea4b)

### The OS that UpSnap is running on

Ubuntu 22.04

### Version of UpSnap

5.0.2

### Your docker-compose.yml content

```YAML
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:5.0.2
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    environment:
       - TZ=Europe/Rome # Set container timezone for cron schedules
       - UPSNAP_INTERVAL=*/3 * * * * * # Sets the interval in which the devices are pinged
    #   - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
       - UPSNAP_WEBSITE_TITLE=WOLSLM # Custom website title
       - UPSNAP_PING_PRIVILEGED=true
    # # dns is used for name resolution during network scan
    dns:
       - 192.168.30.12
       - 192.168.20.11
    # # you can change the listen ip:port inside the container like this:
    # entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    # healthcheck:
    #   test: curl -fs "http://localhost:5000/api/health" || exit 1
    #   interval: 10s
    # # or install custom packages for shutdown
    entrypoint: /bin/sh -c "apk update && apk add --no-cache wget && rm -rf /var/cache/apk/* && wget https://www.SITE.it/media/files/logo.svg && ./upsnap serve --http 0.0.0.0:8090
```

### Reproduction steps

```bash
1.
2.
3.
...
```
