### ISSUE TITLE
Blank page, app not loading, high CPU usage

### ISSUE THREAD

**Issue by DaWy** [seriousm4x/UpSnap#149]
**Describe the bug**
Blank page. Some app assets seems to stop loading. HIGH CPU Usage very suspicious, dont undestand why a simple webapp is wasting that CPU. 

**To Reproduce**
Pulled last image (I saw there was new image). Then recreate the container using following docker-compose file:
```
version: "3"
services:
    upsnap:
        container_name: upsnap3
        network_mode: host
        image: ghcr.io/seriousm4x/upsnap:3
        restart: unless-stopped
        volumes:
          - ./data:/app/pb_data
```
Tried to reset de DB data back, but still the white page...

**Expected behavior**
Well, just APP loading, but does not. 

**Logs**
```
upsnap  | [INFO] 2023/08/02 18:06:06 pb.go:208: Ping interval set to @every 3s
upsnap  | 2023/08/02 18:06:06 Server started at http://0.0.0.0:8090
upsnap  |  ➜ REST API: http://0.0.0.0:8090/api/
upsnap  |  ➜ Admin UI: http://0.0.0.0:8090/_/
```

**Screenshots**
After first request:
![image](https://github.com/seriousm4x/UpSnap/assets/1610889/4c143fc7-6fbc-49ab-8b2e-68a037887d5a)
Pending requests:
![image](https://github.com/seriousm4x/UpSnap/assets/1610889/b4955354-5bd6-42fa-8428-c05307ef302b)

**Host OS (and version)**
Ubuntu 20.04 LTS

**Host Architecture**
amd64

**Browser (if relevant)**
Tried with Edge + Chrome, the same.
