### ISSUE TITLE
[BUG] Upsnap not fetching devices

### ISSUE THREAD

**Issue by RadNotRed** [seriousm4x/UpSnap#193]
**Describe the bug**
Upsnap won't scan devices, it's running as a container in portainer, not sure if that's the issue but when I attach to the console and run `nmap -sn 192.168.1.0/24` it gets the devices.
If I have to, I can run it as a stack

**To Reproduce**
1) Try to scan for devices on 192.168.1.0/24

**Expected behavior**
It should show the results

**Screenshots**
![image](https://github.com/seriousm4x/UpSnap/assets/80015713/9284f7c8-6c79-4b18-9139-b3603cdb58ee)

**Host OS (and version)**
Debian 5.10.179-1

**Host Architecture**
amd64

**Comment by seriousm4x** [comment]
Cloud you try it with the exact command [as in the code](https://github.com/seriousm4x/UpSnap/blob/master/backend/pb/handlers.go#L148)?
So basically `nmap -sn -oX - 192.168.1.0/24 --host-timeout 500ms`
Maybe the timeout is too low.

**Comment by RadNotRed** [comment]
Works perfectly with that command

**Comment by rivolity** [comment]
Same problem here, I'm running the container through Portainer, the Network scan does not work, despite the container is running as root user, and when running the command `nmap -sn -oX - X.X.X.X/24 --host-timeout 500ms` or `nmap X.X.X.X/24` inside the container it works perfectly.

**Comment by rivolity** [comment]
I have fixed the problem by using the network host and not a portainer network.
after that that just access the app using the ip address of your portainer host X.X.X.X:8090.
Here is my docker-compose.yml
it is similar to this one https://github.com/seriousm4x/UpSnap/blob/master/docker-compose.yml
```
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/upsnap/data:/app/pb_data
    environment:
      - TZ=Europe/Berlin # Set container timezone for cron schedules
      - UPSNAP_INTERVAL=@every 1h # Sets the interval in which the devices are pinged
```
