### ISSUE TITLE
Traefik configuration for UpSnap

### ISSUE THREAD

**Issue by SoulEater45** [seriousm4x/UpSnap#27]
This isn't much of an issue, but just a small note on how to configure UpSnap to be used behind Traefik.
Since `network_mode: host` needs be used for scanning the local network, I needed to make a [dynamic config file](https://doc.traefik.io/traefik/providers/file/):
```yaml
http:
  routers:
    lan:
      rule: "Host(`upsnap.example.com`)"
      entryPoints:
        - websecure
      service: lan
      tls:
        certResolver: myresolver
    lan-backend:
      rule: "Host(`upsnap.example.com`) && PathPrefix(`/wol`)"
      entryPoints:
        - websecure
      service: lan-backend
      middlewares:
        - sslheader@file
      tls:
        certResolver: myresolver
  middlewares:
    sslheader:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
  services:
    lan:
      loadBalancer:
        servers:
          - url: "http://1.2.3.4:8000"
    lan-backend:
      loadBalancer:
        servers:
          - url: "http://1.2.3.4:8001"
```

If you don't care about the scanning feature, you can also use labels to configure your container:
```yaml
version: '3.5'

services:
  upsnap:
    image: seriousm4x/upsnap:latest
    container_name: upsnap
    restart: unless-stopped
    environment:
      - FRONTEND_PORT=8000
      - BACKEND_PORT=8001
      - BACKEND_IS_PROXIED=true # set this to true, if you use a reverse proxy
      - DB_TYPE=sqlite
      - REDIS_HOST=upsnap-redis
      - REDIS_PORT=6379
      #- PING_INTERVAL=5 # optional (default: 5 seconds)
      #- DJANGO_SUPERUSER_USER=admin # optional (default: backend login disabled)
      #- DJANGO_SUPERUSER_PASSWORD=admin # optional (default: backend login disabled)
      #- DJANGO_SECRET_KEY=secret # optional (default: randomly generated)
      #- DJANGO_DEBUG=True # optional (default: False)
      #- DJANGO_LANGUAGE_CODE=de # optional (default: en)
      #- DJANGO_TIME_ZONE=Europe/Berlin # optional (default: UTC)
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./db/:/app/backend/db/
    networks:
      - web
      - default
    labels:
      traefik.enable: 'true'
      traefik.docker.network: web
      # Frontend
      traefik.http.routers.upsnap.rule: Host(`upsnap.example.com`)
      traefik.http.routers.upsnap.tls.certresolver: myresolver
      traefik.http.routers.upsnap.entrypoints: websecure
      traefik.http.services.upsnap.loadbalancer.server.port: 8000
      # Backend
      traefik.http.routers.upsnap-backend.rule: Host(`upsnap.example.com`) && Path(`/wol`)
      traefik.http.routers.upsnap-backend.tls.certresolver: myresolver
      traefik.http.routers.upsnap-backend.entrypoints: websecure
      traefik.http.routers.upsnap-backend.middlewares: sslheader
      traefik.http.middlewares.sslheader.headers.customresponseheaders.X-Forwarded-Proto: https
      traefik.http.services.upsnap-backend.loadbalancer.server.port: 8001
      
  redis:
    image: redis:alpine
    container_name: upsnap-redis
    restart: unless-stopped
    command: redis-server --loglevel warning
    healthcheck:
      test: redis-cli ping
      interval: 10s
    networks:
      - default

networks:
  default:
    name: upsnap-net
  web:
    external: true
```

I am not sure if the docker compose file will work, but the dynamic config works just fine! I have seen that using traefik, you could somehow configure containers with `network_mode: host` using `extra_hosts` (you can lookup [this](https://gist.github.com/gaieges/936bdf91e01e4cc782eb047e5873089b) discussion), but I didn't succeed in doing it.

Nevertheless, the config above works for me and maybe it will help someone debug their problems in the future if trying it on their own. I spent like 1-2 hours to figure out that the missing piece was the missing `sslheader` middleware.
