### ISSUE TITLE
UpSnap does not work with docker-compose

### ISSUE THREAD

**Issue by JordyEGNL** [seriousm4x/UpSnap#40]
Hi, I tried using the following docker-compose file, but I can't access the website on 192.168.2.33:8090. it seems that the container is not listening on 0.0.0.0:8090.
```
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:3
    restart: unless-stopped
    volumes:
      - /docker_data/upsnap/data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - TZ=Europe/Amsterdam # Set container timezone for cron schedules
      - UPSNAP_INTERVAL=@every 30s # Sets the interval in which the devices are pinged
      - UPSNAP_SCAN_RANGE=192.168.2.0/24 # Scan range is used for device discovery on local network
    network_mode: host
```

**sudo netstat -tunlp | grep 8090** gave the following result

`tcp6       0      0 :::8090                 :::*                    LISTEN      937145/./upsnap`

I also tried using Nginx Reverse Proxy as maybe that would work, but it did not.
![image](https://user-images.githubusercontent.com/65036298/216764739-d5c6691b-dfc5-4b6c-988d-5913c487d992.png)

Could you please help me out?
