### ISSUE TITLE
[BUG] Only the last user in the list can be deleted

### ISSUE THREAD

**Issue by Weaselfox** [seriousm4x/UpSnap#407]
### The bug

If I created more than one user they are displayed in a list. EG. User1 and User2. The list is alphabetically sorted, so the User1 is on top. If I now try to delete this first User1 a message appears which confirms to delete User2 which is the last of the list.

### The OS that UpSnap is running on

Ubuntu 22.10

### Version of UpSnap

docker image ghcr.io/seriousm4x/upsnap:latest

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap_test
    image: ghcr.io/seriousm4x/upsnap:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./UpSnap:/app/pb_data
# # To use a non-root user, create the mountpoint first (mkdir data) so that it has the right permission.
# user: 1000:1000
    environment:
      - TZ=Europe/Berlin # Set container timezone for cron schedules
      - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
      - UPSNAP_SCAN_RANGE=192.168.10.0/23 # Scan range is used for device discovery on local network
#   - UPSNAP_SCAN_TIMEOUT=500ms # Scan timeout is nmap's --host-timeout value to wait for devices (https://nmap.org/book/man-performance.html)
#   - UPSNAP_PING_PRIVILEGED=true # Set to false if you don't have root user permissions
      - UPSNAP_WEBSITE_TITLE=PC Aufwecken # Custom website title
# # dns is used for name resolution during network scan
# dns:
#   - 192.18.0.1
#   - 192.18.0.2
# # you can change the listen ip:port inside the container like this:
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    healthcheck:
      test: curl -fs "http://localhost:5000/api/health" || exit 1
      interval: 10s
```

### Reproduction steps

```bash
1. Go to "User"
2. Create User1
3. Create User2
4. Try to delete User1 -> User2 will be deleted
...
```
