### ISSUE TITLE
[REQUEST] Edit upsnap port number on docker-compose

### ISSUE THREAD

**Issue by jo-chemla** [seriousm4x/UpSnap#44]
Hi there, I cannot set the port number for a docker container based on the new version of upsnap.

I'm deploying a container based on the ghcr image, but port 8090 is already in use on my host. Since host network mode is needed for network discovery, I wanted to edit the port upsnap is using directly in the docker-compose file. So I tried setting FRONTEND_PORT and BACKEND_PORT env variables (as were used in the previous version of upsnap), or simply the PORT env variable, but upsnap was still listening at port 8090 at startup. 

Is there a way to edit the upsnap port for the docker-compose file? Thanks!

**Comment by seriousm4x** [comment]
Hi, you can just use the `entrypoint` for that:
```
version: "3"
services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:3
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:yourport"
```
