### ISSUE TITLE
[BUG] App resets title setting to "Custom name"

### ISSUE THREAD

**Issue by stv0g** [seriousm4x/UpSnap#455]
### The bug

Maybe related to #242, the app seems to reset the title setting to "Custom name" quite frequently. I couldnt figure out when this happens though. Other settings like the configured hosts are unaffacted.

### The OS that UpSnap is running on

Docker (upsnap:4)

### Version of UpSnap

4.2.0

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    # # To use a non-root user, create the mountpoint first (mkdir data) so that it has the right permission.
    # user: 1000:1000
    environment:
    - TZ=Europe/Berlin # Set container timezone for cron schedules
    - UPSNAP_INTERVAL=@every 20s # Sets the interval in which the devices are pinged
    - UPSNAP_SCAN_RANGE=10.168.10/23 # Scan range is used for device discovery on local network
    - UPSNAP_SCAN_TIMEOUT=500ms # Scan timeout is nmap's --host-timeout value to wait for devices (https://nmap.org/book/man-performance.html)
    - UPSNAP_PING_PRIVILEGED=true # Set to false if you don't have root user permissions
    - UPSNAP_WEBSITE_TITLE=Custom name # Custom website title
    dns:
      - 10.168.11.1
      - 10.168.10.1
    # # you can change the listen ip:port inside the container like this:
    # entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    # healthcheck:
    #   test: curl -fs "http://localhost:5000/api/health" || exit 1
    #   interval: 10s
    # # or install custom packages for shutdown
    # entrypoint: /bin/sh -c "apk update && apk add --no-cache <YOUR_PACKAGE> && rm -rf /var/cache/apk/* && ./upsnap serve --http 0.0.0.0:8090"
```

### Reproduction steps

```bash
1. Start Docker containers
2. Add a host
3. Change title setting
4. Come back some hours later, reload page?
5. Title setting has been reverted to "Custom name"
```
