### ISSUE TITLE
[BUG] Not waking up

### ISSUE THREAD

**Issue by Irix0** [seriousm4x/UpSnap#485]
### The bug

Hi,

I'm currently running docker on Alpine Linux. I tried to setup UpSnap different ways but I did not suceed to make it work (correctly).

I tried to send the magic packet from the container itself and it works. I'm currently using awake to send the packet.

I'm using 255.255.255.255 as a subnet mask.

I'm not receiving packets using the wake on lan monitor.

### The OS that UpSnap is running on

Alpine

### Version of UpSnap

latest

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    entrypoint: /bin/sh -c "apk update && apk add awake && ./upsnap serve --http 0.0.0.0:8090"
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
networks: {}
```

### Reproduction steps

```bash
1. Use the docker-compose
2. Add a device
3. Wake up is not working
...
```
