### ISSUE TITLE
Unable to Wake from Web-UI

### ISSUE THREAD

**Issue by dey-d** [seriousm4x/UpSnap#561]
### The bug

Hi, thanks for this great project. I can't seem to be able to get my computer to wake from the web-ui. The web-ui registers when the PC is on but when I send the magic packet by triggering the button It doesn't seem to be working. I just set up the container today so assuming its using the latest version.

I am able to turn the PC on with a WOL phone app. 

I have tried going ino the docker container and executing awake [MAC] which works and turns on the PC so don't think its do with any container network issue.  
- Sending magic packet to 255.255.255.255 with broadcast 255.255.255.255 MAC 10:C3:7B:##:##:## port 9

Below is my set up: 

<img width="1253" alt="image" src="https://github.com/seriousm4x/UpSnap/assets/98645865/05f61412-bb31-4cc6-a781-89092a882157">

Any ideas? 

Thanks!

### The OS that UpSnap is running on

Ubuntu 22.04

### Version of UpSnap

4.2.9

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - /root/upsnap/data:/app/pb_data
    ports:
      - 8090:8090
    environment:
       - TZ=Europe/London # Set container timezone for cron schedules
       - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
       - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
```

### Reproduction steps

```bash
1. New docker install of UpSnap
2. Tried with 255.255.255.255 and 255.255.255.0
3. Tried sending magic packet by triggering on button which was unsuccessful.
3. Executed awake command from container which was successfull
```
