### ISSUE TITLE
[BUG] Online status is always indicated as offline

### ISSUE THREAD

**Issue by Shadow27374** [seriousm4x/UpSnap#563]
### The bug

Waking up works perfectly, but unfortunately the PC is still displayed as switched off (red button).

### The OS that UpSnap is running on

Ubuntu 22.04.4 LTS

### Version of UpSnap

4.2.9

### Your docker-compose.yml content

```YAML
upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/sysadmin/docker/upsnap:/app/pb_data
    user: 1000:1000
    environment:
      - TZ=Europe/Berlin
      - UPSNAP_SCAN_RANGE=192.168.0.0/24
    dns:
      - 192.168.0.110
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:8091"
    healthcheck:
      test: curl -fs "http://localhost:8091/api/health" || exit 1
      interval: 10s
```

### Reproduction steps

```bash
1. Click on the power button
2. Check whether the PC starts
3. Wait 2 minutes for the button to be clickable again
4. Button is red again
```

### Additional information

Uncomplicated Firewall (UFW) switched off as a test.
Instead of using a reverse proxy (Traefik), I tried it directly via IP:Port.
