### ISSUE TITLE
[BUG] UpSnap Doesn't WOL With IP Address

### ISSUE THREAD

**Issue by firefly2442** [seriousm4x/UpSnap#583]
### The bug

I was having trouble getting UpSnap to wake a machine.  I tested to make sure I could get it working outside UpSnap.

```
wakeonlan <macaddress>
```

This works.  Then I tried within the container.

```
docker exec -it <id> sh
apk update
apk add awake
awake <macaddress>
```

This worked.  However, when I try adding the IP address, anything I try fails.

```
awake -d 192.168.1.112 <macaddress>
awake -d 192.168.1.1 <macaddress>
awake -d 192.168.0.1 <macaddress>
```

In the UI, the IP address is marked as required.  I wonder if perhaps this may not be needed and it should be optional?

### The OS that UpSnap is running on

Ubuntu 22.04 (pi4)

### Version of UpSnap

4.2.9

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=America/Chicago # Set container timezone for cron schedules
    healthcheck:
      test: curl -fs "http://localhost:8090/api/health" || exit 1
      interval: 10s
```

### Reproduction steps

```bash
See above steps for testing using `awake`.
```

### Additional information

Thanks
