### ISSUE TITLE
[BUG] Wake on Lan with the IP Address field doesnt work.

### ISSUE THREAD

**Issue by crouch010** [seriousm4x/UpSnap#635]
### The bug

The problem is that when i press the button WAKE on the Upsnap web interface it doesnt work, i checked with wireshark and i am almost 100% sure that it doesnt send any kind of wol packet onto the network.

I tried what another user said here to use awake command and it workes perfectly fine but when i add the IP Address it stops working.. issue #583 

What can be the issue? I belive i ma not the only one.

### The OS that UpSnap is running on

Ubuntu Server 22.04.4

### Version of UpSnap

4.2.11

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    networks:
      macvlan:
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/upsnap-data:/app/pb_data
    #environment:
    #  - TZ=Europe/Bucharest
    #dns:
    #  - 192.168.1.12
    #  - 192.168.1.26

networks:
  macvlan:
    external: true
```

### Reproduction steps

```bash
1. when using the wol button in the interface.
```
