### ISSUE TITLE
[BUG] devices gone and editing devices throws error 403

### ISSUE THREAD

**Issue by swoop124** [seriousm4x/UpSnap#65]
**Describe the bug**
I connected to my upsnap instance to start my Remote PC. But as i connect there was a request to create an Admin-Account. So i created one. But all entryes of Remote PCs were gon.
So i tried to create one of the Remote-PCs. But when i create one i get this error:
`Failed: ClientResponseError 403: Only admins can perform this action`

**To Reproduce**
1. Go to web interface
2. Click on Settings
3. Enter Name, IP and MAC
4. Cllick Add device
5. see error

**Expected behavior**
The Device should be added

**Logs**
```
upsnap  | [INFO] 2023/03/25 13:15:41 pb.go:208: Ping interval set to @every 10s
upsnap  | 2023/03/25 13:15:41 Server started at http://0.0.0.0:8090
upsnap  |  ➜ REST API: http://0.0.0.0:8090/api/
upsnap  |  ➜ Admin UI: http://0.0.0.0:8090/_/
```

**Screenshots**
![grafik](https://user-images.githubusercontent.com/75502165/227717431-2065aba3-9db3-4380-843a-49486cbdf19c.png)

**Host OS (and version)**
Debian 11.

**Host Architecture**
amd64

**Brower (if relevant)**
Firefox 111, Edge  111 (64-Bit)

**Additional context**
i also created a brand new database. Same error

**Comment by seriousm4x** [comment]
> But all entryes of Remote PCs were gon

Check at [127.0.0.1:8090/_/](http://127.0.0.1:8090/_/), login and click devices if they are still there.

>  So i tried to create one of the Remote-PCs. But when i create one i get this error:
Failed: ClientResponseError 403: Only admins can perform this action

Error 403 means that you are logged in as a normal user who doesn't have permission to edit devices. Log back in with an admin account to edit devices. Maybe also clear local storage and see if that helps.

**Comment by swoop124** [comment]
Hello, 

thank you for your answer.

the problem is, i have logged in als Admin. There are no other users.

**Comment by swoop124** [comment]
i just tried to login to Usermanagement but i get this error:
`The request requires valid admin authorization token to be set.`

how can i verify that my user is a admin? When my user is the only user registered?

**Comment by seriousm4x** [comment]
Do you check the "Admin login" toggle on the login page?
If you are not an admin user, you will see this box when visiting /settings or edit devices
![2023-03-26 01_18_56](https://user-images.githubusercontent.com/23456686/227748499-2e12d571-8848-4a45-840c-0b6c4b0dc100.png)

**Comment by swoop124** [comment]
yes

**Comment by seriousm4x** [comment]
Are you getting any browser console errors when pressing F12?

**Comment by swoop124** [comment]
yes.

Error: Permission denied to access property "ownerDocument"
Uncaught (in promise) ClientResponseError 403: Only admins can perform this action.
    Immutable 2
        n
        Ct


now i am testing with another Computer.

**Comment by swoop124** [comment]
Oh, i forgot. I am using "Nginx Proxy Manager" as a Reverse Proxy.

**Comment by seriousm4x** [comment]
> Oh, i forgot. I am using "Nginx Proxy Manager" as a Reverse Proxy.

Thats no problem. I use it too.

I can't reproduce your error from the steps you gave me in your first message. Can you give me exact steps what you do after the first start?

**Comment by swoop124** [comment]
hello,

i created a Windows ScreenRecording. I hope you can use this. 
If not i will think of another way.
[Screenrecording.zip](https://github.com/seriousm4x/UpSnap/files/11071020/Screenrecording.zip)

**Comment by seriousm4x** [comment]
Ok, I got the screenshots to show in Microsoft Word 😆 (Not sure if thats the best way to open this file) But seems like you did nothing wrong there.
Still don't know how to reproduce this.

**Comment by swoop124** [comment]
i've tried to access upsnap without npm, i could save now, without error. But when i access via npm the entry is not there anymore. 
But i would prefer to use npm.

with this docker-compose.yml i start my instance:
```
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:3
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - TZ=Europe/Berlin # Set container timezone for cron schedules
      - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
    #   - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
    #   - UPSNAP_WEBSITE_TITLE=Custom name # Custom website title
    # command: ["./upsnap", "serve", "--http", "0.0.0.0:8090"] # Uncomment this if you want to change the port for example
```

At first all environment variables were commented.

**Comment by seriousm4x** [comment]
I use the same docker-compose as you and use basically the default settings in npm:
![npm](https://user-images.githubusercontent.com/23456686/227768263-f074b841-e742-4bc5-8610-374ec1e40622.jpg)
Works just fine for me. No errors.

**Comment by swoop124** [comment]
I just tested it with your settings fon npm, but no change.
Could it be filepermissions?
I am out of ideas...

It worked til about a week or two ago. Yesterday as i used it again, I dont use it very often, there was the message, that i have to create an Adminuser. I think Watchtower made an update.
But as i said above, i tried to recreate the container with empty folder.

**Comment by swoop124** [comment]
Hello again,

i just testet to install upsnap an a brandnew docker-host. but get the same error.
i am logedin as Admin, no other User is present.

But when i don't use my nginx proxy manager, it is working just fine. So where is the Problem? is it on my side? But i don't kow where to search. Because all other Services are running over NPM and work great.

Oh, i observed something. When NOT using NPM i can login as Admin and add a new host, without errormessage. Then when i use NPM and login as same Admin-User, as bevore, there is no sign of the newly created Host. 

Any Ideas or recomendations?

**Comment by swoop124** [comment]
Hello,

thanks for your reply.
These are my NPM-Settings:
![grafik](https://user-images.githubusercontent.com/75502165/231215265-9978640c-ca5d-4d18-b60f-ab4133f8ad31.png)
![grafik](https://user-images.githubusercontent.com/75502165/231215513-995a20bd-fbda-4a52-b55e-694b9f898d77.png)
no locations or Advanced Settings
I've even testet it without ssl.

DNS from the docker host 4 network, i am using, is working fine. Ipv4 and Ipv6.
I habe multiple docker hosts. So routing is OK. 
As you said, it's weird.

As i mentioned, it worked fine til i enabled watchtower update. Then i was not using upsnap for longer, til 2 or 3 weeks ago.
After an update, there was a message, i have to generate an Admin User. So I did. Than there was none of my entrys there. 
The first thing I did was to create a brandnew instance, but same error.
The weireder thing is, there are no messages from docker or anything i know of.

Is there inside of Upsnap a Log-file or something that would be helpful?

**Comment by seriousm4x** [comment]
Just tried it with the exact same npm settings as you in our office network where we also use different subnets.
Still can't replicate your issue :/ Sorry.

Maybe it's got something to do with ipv6 because we have disabled that in our office network. But I use ipv6 in my home network on the other hand. Kinda clueless.

Don't know why to try on my end anymore. Let me know if you happen to find out a solution.

**Comment by lino-silva** [comment]
Can confirm the exact same behaviour - works when accessing via IP, does not work when accessing via SWAG (nginx). 

I'm using the default `docker-compose.yml`, container is running inside an LXC on top of Proxmox. The whole setup is created using ansible, and I'm able to reproduce this consistently.

Let me know if you need something on my side to help debug.

**Comment by lino-silva** [comment]
Additional context: when logging in, the `/api/admins/auth-with-password` runs successfully and I receive the same info on either URLs - but for some reason, my localStorage looks like this accessing via IP: 
<img width="261" alt="image" src="https://github.com/seriousm4x/UpSnap/assets/1109759/3e8fcdfb-7919-479f-831a-b7ca205cadb6">
But it looks like this with a reverse proxy on front:
<img width="133" alt="image" src="https://github.com/seriousm4x/UpSnap/assets/1109759/c5bd640d-09b9-4c6c-a009-4bbc76b3cb63">

**Comment by seriousm4x** [comment]
> I'm using the default docker-compose.yml, container is running inside an LXC on top of Proxmox. The whole setup is created using ansible, and I'm able to reproduce this consistently.

I'm really trying hard here to replicate this :D Here is what I tried:

1. I've created a vm in virtual manger, assined it a bridged network and installed proxmox ve 8.0.3 (DHCP gave the vm the ip `10.1.1.68`)
2. Inside my local DNS server (I use adguard) I setup a new DNS record for `*.kekl.com` and pointed it to `10.1.1.68` (the proxmox vm)
3. As I'm not familiar with SWAG, I've used Nginx Proxy Manager again (as the original poster also used it) and set a reverse proxy like so:
![Screenshot 2023-08-17 at 22-00-33 Nginx Proxy Manager](https://github.com/seriousm4x/UpSnap/assets/23456686/59320b54-20d4-4042-8c98-c6665a1afd57)
5. Next, I've setup a debian 12 LXC container inside proxmox
![Screenshot 2023-08-17 at 21-59-24 proxmox - Proxmox Virtual Environment](https://github.com/seriousm4x/UpSnap/assets/23456686/a1b85463-5712-41d4-9fb2-e855c595ada6)
6. Then installed docker, and stared up UpSnap with the default docker-compose config
7. Went to `pve.kekl.com` and UpSnap seems to work just fine. All api routes, everything.
![swappy-20230817_220143](https://github.com/seriousm4x/UpSnap/assets/23456686/aacbe4c6-6ace-484e-8648-059fa54f6be1)

Also, I'm not quite sure where all of your local storage items are coming from @lino-silva . Especially those `something@hidden` items. There are just 2 lines of code where I set local storage items. It's `orderBy` and `orderByGroups`. Here are those [lines](https://github.com/search?q=repo%3Aseriousm4x%2FUpSnap%20localstorage.setitem&type=code). This is what my local storage looks like:
![swappy-20230817_220243](https://github.com/seriousm4x/UpSnap/assets/23456686/107bd196-67b3-4f0a-a6f5-5ef429d2961a). It's probably from some other dashboard thats running on the same ip.

I don't know if there is a major oversight on my part why it's not working for both of you. Let me know if there is something different with my setup in comparison to yours.

**Comment by lino-silva** [comment]
It's bizarre - I've just tried running the binary itself inside a LXC, via `./upsnap serve --http=0.0.0.0:8090` and the result is the same, so it has nothing to do it docker it seems.

Incognito does nothing as well, tried both Chrome and Firefox. The behaviour is always the same:

- Spin up a clean version of UpSnap
- Set up reverse proxy through [swag]https://github.com/linuxserver/docker-swag/tree/master/root/defaults/nginx) by adding a subdomain specific file (I used [this one](https://github.com/linuxserver/reverse-proxy-confs/blob/master/mealie.subdomain.conf.sample)  as a reference)
- Access it through subdomain
- Create admin account
- Try to access "Settings" page
- Breaks

Same flow through the IP, works flawlessly.

**Comment by seriousm4x** [comment]
> Edit2: Those values come from PocketBase's admin panel afterall. To add, I'm not able to log-in to the panel with the reverse-proxy as well, so that's consistent.

So accessing the pocketbase backend at `/_/` with reverse proxy doesn't work as well?
If so, it seems like an upstream issue with pocketbase directly.

**Comment by lino-silva** [comment]
So it seems.

**Comment by seriousm4x** [comment]
So, [I asked the author of Pocketbase](https://github.com/pocketbase/pocketbase/discussions/3170#discussioncomment-6784241) if he had any ideas. His response was essentially that we need precise reproducible steps. Without these, we cannot identify the problem.

**If someone is experiencing the issue and can provide an exact step-by-step guide** (similiar to [what I did](https://github.com/seriousm4x/UpSnap/issues/65#issuecomment-1682933282), screenshots would be nice as well), **I'd be happy to try to resolve the problem.**

**Comment by swoop124** [comment]
hello,
i follow this thread since  i created it. I try to descripe exactly how i got the error.
At my first install of Upsnap there was no problem, but after some automatic updates via watchtower, suddenly there was this problem.
So here is my setup:

1. I created a Proxmox VM for my Nginx Proxy Manager. The Proxmox and VM is located in DMZ.
![grafik](https://github.com/seriousm4x/UpSnap/assets/75502165/46accaa0-e80a-46fd-95b3-2127011143a5)
2. Than i installed Debian 11 and docker, as described in docker-docs. After the descovery of this problem, i upgradet it to Debian bookworm (12).
3. Then i created the NPM-Dockercontainer via this docker-compose.yml:
```
version: "3"
services:
  app:
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npmuser
      - DB_MYSQL_PASSWORD=xxxxxxxxxx
      - DB_MYSQL_NAME=npm
    image: jc21/nginx-proxy-manager:latest
    # image: jc21/nginx-proxy-manager:github-pr-2599
    networks:
      npm_test:
        ipv6_address: xxx:xxxx:xxxx:xxxx:xxxx:ac11:1001
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 81:81/tcp
    restart: always
    volumes:
      - /opt/npm/letsencrypt:/etc/letsencrypt:rw
      - /opt/npm/data:/data:rw
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxx
      - MYSQL_DATABASE=xxxxxxxx
      - MYSQL_USER=npmuser
      - MYSQL_PASSWORD=xxxxxxxx
    image: jc21/mariadb-aria:latest
    networks:
      - npm_test
    restart: always
    volumes:
      - /opt/npm/data/mysql:/var/lib/mysql:rw

networks:
  npm_test:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: xxx:xxxx:xxxx:xxxx::/64
```
4. Then i added some reverse proxy entrys such as for Upsnap:
![grafik](https://github.com/seriousm4x/UpSnap/assets/75502165/9e80a3b1-a820-49fc-aaa8-e05aa3602368)
After many tests i endet up with this settings:
![grafik](https://github.com/seriousm4x/UpSnap/assets/75502165/f1336707-c1c9-4e12-9605-69654983d1a8)
![grafik](https://github.com/seriousm4x/UpSnap/assets/75502165/e9568553-a8be-4669-9c3a-7868742ef8fb)
![grafik](https://github.com/seriousm4x/UpSnap/assets/75502165/ae45f29f-3910-40a0-b9f3-0a2f80853e76)
5. Then i created a LXC (Debian 11) on a Proxmox Server that is located in LAN and installed Docker als described in the docker-docs.
![grafik](https://github.com/seriousm4x/UpSnap/assets/75502165/16d87a9c-0005-4517-af06-750b9798f033)
6. In this LXC are running several docker-container. One of them is Upsnap. I used this docker-compose.yml
```
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:3
    #image: ghcr.io/seriousm4x/upsnap:3.1.1
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - TZ=Europe/Berlin # Set container timezone for cron schedules
      - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
    #   - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
    #   - UPSNAP_WEBSITE_TITLE=Custom name # Custom website title
    # command: ["./upsnap", "serve", "--http", "0.0.0.0:8090"] # Uncomment this if you want to change the port for example
```
Now there ist this odd error when i used the url i created in NPM.

What i have done so far:
I updated all participated linux and docker.
I changed hosts for docker and installed all requirements and docker-containers involved. I used lxc for these test, but no difference.
