### ISSUE TITLE
[BUG] Wake cron not executed

### ISSUE THREAD

**Issue by levelsw** [seriousm4x/UpSnap#669]
### The bug

I have a wake cron scheduled daily (0 22 * * *), I seem to be having some issues where it doesn't execute it (randomly). It was missed the 8th of July and also Yesterday evening (No log entry for it, so it seems like it's not even trying):

`[INFO] 2024/07/08 23:05:14 wake.go:16: Wake triggered for Veeam Server (Integrated NIC)`
`[INFO] 2024/07/09 13:34:59 wake.go:16: Wake triggered for Veeam Server (Integrated NIC)`
`[INFO] 2024/07/09 22:00:00 wake.go:16: Wake triggered for Veeam Server (Integrated NIC)`
`[INFO] 2024/07/11 16:31:25 wake.go:16: Wake triggered for Veeam Server (Integrated NIC)`

### The OS that UpSnap is running on

Ubuntu 22.04.3 LTS

### Version of UpSnap

4.2.11

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=Europe/Amsterdam # Set container timezone for cron schedules
    dns:
      - X.X.X.X
      - Y.Y.Y.Y
```

### Reproduction steps

```bash
1. Schedule wake cron
2. Wait for it to fail
```
