### ISSUE TITLE
[BUG] Cant WOL

### ISSUE THREAD

**Issue by olivertd** [seriousm4x/UpSnap#706]
### The bug

I cannot wake on lan the computer, I have a program on my mac called wake me up , It works perfectly fine, But when i take the mac adress, Ip, Subnet etc everything into UpSnap, I cant get it to work, Im not sure if im doing something wrong (Probably) but i can not figure it out. Is there any common reasons for this to be happening?

### The OS that UpSnap is running on

Ubuntu Server 

### Version of UpSnap

4.2.10

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=Europe/Berlin # Adjust to your timezone
      - UPSNAP_INTERVAL=@every 10s
      - UPSNAP_SCAN_RANGE=192.168.1.0/224 # Adjust to your network
      - UPSNAP_SCAN_TIMEOUT=500ms
      - UPSNAP_PING_PRIVILEGED=true
    dns:
      - 192.168.1.1 # Adjust to your router's IP or preferred DNS
    ports:
      - 8090:8090
    # Uncomment if you need to install additional packages
    # entrypoint: /bin/sh -c "apk update && apk add --no-cache iputils && rm -rf /var/cache/apk/* && ./upsnap serve --http 0.0.0.0:5000"

networks: {}
```

### Reproduction steps

```bash
1. go into upsnap
2. try to wol
3. not working
4. maybe something wrong in my docker compose?
...
```
