### ISSUE TITLE
[BUG] Ui to standard when Authelia is used

### ISSUE THREAD

**Issue by XHyperDEVX** [seriousm4x/UpSnap#715]
### The bug

Thanks for UpSnap!

I'm using it on Docker with NPM (NGINX Proxy Manager) and want to use it behind [Authelia](https://www.authelia.com/) as an additional layer of security.

However, when I add the Authelia code in NPM, open UpSnap via it and log in, the UI appears, but without my set up devices (+ my favicon is gone). When I remove the Authelia code again, everything loads normally again. Apparently UpSnap is not compatible with Authelia.

Since I don't know how UpSnap works, I hope one of you can tell me which part of Authelia (see below) is interfering with UpSnap.

This is the Authelia config for NPM:
```
include /snippets/authelia-location.conf;

location / {
    include /snippets/proxy.conf;
    include /snippets/authelia-authrequest.conf;
    proxy_pass $forward_scheme://$server:$port;
}
```

I have attached the files mentioned in the script. (I have renamed it to .txt so that GitHub will accept it)
[authelia-authrequest.txt](https://github.com/user-attachments/files/16501210/authelia-authrequest.txt)
[proxy.txt](https://github.com/user-attachments/files/16501211/proxy.txt)
[authelia-location.txt](https://github.com/user-attachments/files/16501213/authelia-location.txt)

I am very grateful for any help! <3

### The OS that UpSnap is running on

Docker

### Version of UpSnap

4.2.12 (newest)

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - /data/upsnap:/app/pb_data
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:4444"
```

### Reproduction steps

```bash
Install UpSnap
Setup some Devices in the UI
Add the Authelia Code to NGINX Config
```
