### ISSUE TITLE
[BUG] [Docker] Cannot Start Main Process: exec container process `/app/./upsnap`: Operation not permitted

### ISSUE THREAD

**Issue by m1nicrusher** [seriousm4x/UpSnap#722]
### The bug

Hi I'm using `podman` to run the docker image on RHEL 9. The reason why I'm not using `docker` is because `podman` replaces `docker` completely on RHEL and it is a pain to switch to docker (on RHEL, docker is an alias to podman so installing docker will get podman installed by default). Plus, all of my other docker images works just fine using podman.

When I start the container it keeps says this
```
{"msg":"exec container process `/app/./upsnap`: Operation not permitted","level":"error","time":"2024-08-11T10:13:41.148512Z"}
```

Tried both rootless and running as root. SELinux not enabled.

Tried checking `ls` and I can confirm the binary file `upsnap` exists.

The mounted directory has 777 permission and is owned by the user when running rootless.

Any ideas?

### The OS that UpSnap is running on

RHEL 9.4

### Version of UpSnap

Latest from ghcr.io/seriousm4x/upsnap:4

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - /mnt/apps/upsnap:/app/pb_data
```

### Reproduction steps

```bash
1. Create folder /mnt/apps/upsnap
2. `chown` it to user
3. `chmod` it to 777
4. Turn off SELinux
5. Create `docker-compose.yml`
6. `sudo podman-compose up` or `podman-compose up`
7. Error shown and container not running.
```

**Comment by seriousm4x** [comment]
Not quite sure why the path is showing as `/app/./upsnap`. There shouldn't be any dot in between. Maybe thats the issue?

Could you try running the executable directly from the latest release page?

**Comment by seriousm4x** [comment]
I've found a workaround. Seems like on RHEL the compose file needs `privileged: true` to run propeerly.

```yml
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./pb_data:/app/pb_data
    privileged: true
```
