### ISSUE TITLE
[BUG] CPU spikes at consisten intervals

### ISSUE THREAD

**Issue by Progeny42** [seriousm4x/UpSnap#747]
### The bug

I am monitoring UpSnap resource usage. I've noticed that, despite it not being in use, and Lazy Ping enabled, that every, approximately 15 minutes, the CPU usage spikes a few percent.  I only have 2 hosts registered (if that maker a difference)

Here is just the last 3 hours alone
![image](https://github.com/user-attachments/assets/cbffa03c-f006-4f9b-a4e6-e66f02c195ab)

I'm not sure this is necessarily the fault of UpSnap, but perhaps an issue with the Go configuration / web server being used, as I've noticed a very similar issue with Homarr, and to a lesser extent Gotify.

### The OS that UpSnap is running on

Unraid

### Version of UpSnap

4.2.12

### Your docker-compose.yml content

```YAML
As noted, I'm using Unraid, and haven't gotten around to using Docker Compose for this app, instead utilising the built in Unraid CA app template. I've used Composerize, which I know is not perfect here, but should be sufficient for you.

name: <your project name>
services:
    upsnap:
        container_name: UpSnap
        network_mode: host
        environment:
            - TZ=Europe/London
            - HOST_OS=Unraid
            - HOST_HOSTNAME=Orilla
            - HOST_CONTAINERNAME=UpSnap
            - TZ'='Europe/London
        labels:
            - net.unraid.docker.managed=dockerman
            - net.unraid.docker.webui='http://[IP]:[PORT:8090]'
            - net.unraid.docker.icon='https://raw.githubusercontent.com/seriousm4x/unraid-community-apps/master/icons/upsnap.png'
        volumes:
            - /mnt/user/appdata/upsnap/':'/app/pb_data/':'rw
        image: "'ghcr.io/seriousm4x/upsnap:4'"
        command: --http 0.0.0.0:8090
```

### Reproduction steps

```bash
Just run UpSnap.
```
