### ISSUE TITLE
Update wiki articles

### ISSUE THREAD

**Issue by B4DschK4Pp** [seriousm4x/UpSnap#948]
## API wiki

[https://github.com/seriousm4x/UpSnap/wiki/Rest-API](https://github.com/seriousm4x/UpSnap/wiki/Rest-API)

I want to use the api to start up my PC via script and had major troubles understanding what had to be done.

Finally I realized that the api endpoint for creating a token for a superuser is not correct in the wiki article. Instead of ``/api/admins/auth-with-password`` it now should be ``/api/collections/_superusers/auth-with-password``.

## Auth providers

[https://github.com/seriousm4x/UpSnap/wiki/Auth-providers](https://github.com/seriousm4x/UpSnap/wiki/Auth-providers)

I came across the auth providers wiki article and tried to find the mentioned settings page in my environment, but was out of luck. Is the article outdated? Or is my environment missing some packages? 

### The OS that UpSnap is running on

docker

### Version of UpSnap

4.5.1

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - /volume1/docker/upsnap/data:/app/pb_data
    environment:
      - TZ=Europe/Berlin # Set container timezone for cron schedules
    #   - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
    #   - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
    #   - UPSNAP_WEBSITE_TITLE=Custom name # Custom website title
    # # dns is used for name resolution during network scan
    dns:
      - 192.168.123.12
    #   - 192.18.0.2
    # # you can change the listen ip:port inside the container like this:
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:8003"
    healthcheck:
      test: curl -fs "http://localhost:8003/api/health" || exit 1
    #   interval: 10s
    # # or install custom packages for shutdown
    # entrypoint: /bin/sh -c "apk update && apk add --no-cache <YOUR_PACKAGE> && rm -rf /var/cache/apk/* && ./upsnap serve --http 0.0.0.0:8090"
```

### Reproduction steps

```bash
not necessary
```
