### ISSUE TITLE
[BUG] Missing Authentication settings - Auth prroviders

### ISSUE THREAD

**Issue by domenico-dig** [seriousm4x/UpSnap#952]
### The bug

In the last update Missing Authentication settings - Auth prroviders

![Image](https://github.com/user-attachments/assets/95742749-177c-4189-81ca-c99a454026db)

### The OS that UpSnap is running on

Ubuntu 22.04

### Version of UpSnap

4.5.1

### Your docker-compose.yml content

```YAML
version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4.5.1
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    environment:
       - TZ=Europe/Rome # Set container timezone for cron schedules
    #   - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
    #   - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
    #   - UPSNAP_WEBSITE_TITLE=Custom name # Custom website title
    # # dns is used for name resolution during network scan
    dns:
       - 192.168.200.10
       - 192.168.200.11
    # # you can change the listen ip:port inside the container like this:
    # entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    # healthcheck:
    #   test: curl -fs "http://localhost:5000/api/health" || exit 1
    #   interval: 10s
    # # or install custom packages for shutdown
    entrypoint: /bin/sh -c "apk update && apk add --no-cache wget && rm -rf /var/cache/apk/* && wget https://www.xxx.it/media/files/xxx-logo.svg && ./upsnap serve --http 0.0.0.0:8090"
```

### Reproduction steps

```bash
1.
2.
3.
...
```
