### ISSUE TITLE
[BUG] Cron not working

### ISSUE THREAD

**Issue by fun4stuff** [seriousm4x/UpSnap#995]
### The bug

After entering cron, it never wakes.

https://github.com/user-attachments/assets/3a1b8060-23d3-496a-bc05-49c0df331c0f

Check out the screen capture video. Shows how I entered Cron syntax. You can tell the time is set using correct syntax but after that set time passes (changes from "today at 2:54pm" to "tomorrow at 2:54pm") the wake command is never sent by upsnap. In the video I wait a minute or so after 2:54 pm passes- but PC never wakes. I then manually click the wake button and it wakes within 30 seconds.

### The OS that UpSnap is running on

Synology docker

### Version of UpSnap

4.2.0

### Your docker-compose.yml content

```YAML
Same as readme
```

### Reproduction steps

```bash
1.set cron
2.wait until set time passes 
3. Computers do not turn on
...
```

### Additional information

/

**Comment by seriousm4x** [comment]
I tried to reproduce it on my end but I can't. Can you provide some browser console logs?

(Open the page on a desktop browser, hit F12, try the cron thing again and check the error logs in the console window.)

**Comment by fun4stuff** [comment]
I updated upsnap to 4.6.1

I do not have any errors in the browser console or in docker container log. 

When I manually wake, it is reported in the docker log. Nothing ever happens in the log after it passes cron time.

**Comment by seriousm4x** [comment]
What timezone are you in? Maybe the docker container has a different timezone than your client.

You can set the timezone in docker compose like [this|(https://github.com/seriousm4x/UpSnap/blob/master/docker-compose.yml#L12):
```yml
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=Europe/Berlin # Set container timezone for cron schedules
```
